# spring.application.name=demo
# spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
# spring.datasource.username=postgres
# spring.datasource.password=Srinivasnani@123
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # JWT properties
# app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8e8f85f8bf5c46e2898aa7424ab3ed8
# app.jwt.expiration-ms=86400000

spring.application.name=demo
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT properties
app.jwt.secret=${APP_JWT_SECRET:change-me-in-render}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
