# spring.application.name=demo
# spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
# spring.datasource.username=postgres
# spring.datasource.password=Srinivasnani@123
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # JWT properties
# app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8e8f85f8bf5c46e2898aa7424ab3ed8
# app.jwt.expiration-ms=86400000

spring.application.name=demo
spring.datasource.url=jdbc:postgresql://dpg-d7fhifnlk1mc73debcb0-a.singapore-postgres.render.com:5432/mydb_vjn4
spring.datasource.username=mydb_vjn4_user
spring.datasource.password=m1mrgWgnz20YiRg8YvPIKWnPDgfTptnG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT properties
app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8e8f85f8bf5c46e2898aa7424ab3ed8

app.jwt.expiration-ms=86400000